### ISSUE TITLE
Request: Option to protect all contrib pages by default

### ISSUE THREAD

**Issue by ghost** [elisseck/com.elisseck.civihoneypot#1]
Hi! Love the extension. Just wondering if you've given thought to making it possible for the extension to apply the honeypot fields/functionality to every contrib page by default.

We have a LOT of contrib pages and we're running multisite which compounds things. Having a default "protect every contrib page" option would be amazing.

Happy to chat here or on the CiviCRM mattermost if you wish.

Cheers!

**Comment by elisseck** [comment]
reference #2
