### ISSUE TITLE
Could this be extended to work for civievents including free ones

### ISSUE THREAD

**Issue by petednz** [elisseck/com.elisseck.civihoneypot#10]

**Comment by elisseck** [comment]
@petednz I believe this type of feature was included in a big contribution getting worked on a while back and I think it got dropped for one reason or another, as things do with volunteer projects:

https://github.com/elisseck/com.elisseck.civihoneypot/pull/5

I'm not 100% sure where this is at, it sounded like what's there was working and they were adding support for additional forms. If you are able to test the pull and see it does what you want it to do... I will just merge it as-is.

I would like to say I can push this feature forward but realistically my schedule is pretty tight these days so I can't make any timeline promises! Happy to review contributions, though. It's been on my list to clean this up for some time.

**Comment by elisseck** [comment]
@petednz I believe Jon's contribution may have resolved this for you so i'll close this issue. I merged it but haven't tagged a new release yet or anything.

 Feel free to re-open it if there is some piece that hasn't been covered and i'll tag a new release hopefully this weekend.
