### ISSUE TITLE
CiviCRM 5.x compatibility

### ISSUE THREAD

**Issue by TechnologyClassroom** [elisseck/com.elisseck.civihoneypot#7]
I noticed that there have not been any commits to the project in a while.  Is the extension still actively developed?  Do you know if it's compatible with CiviCRM 5.x?

**Comment by elisseck** [comment]
Hello @TechnologyClassroom and thanks for checking.

I would say this extension is not _actively_ developed any longer. Active development was originally funded :). I have been spending my limited volunteer dev time on core issues.

I am, however, more than happy to respond to bug reports, feature requests, etc in the form of issues. If you can contribute funding or provide a PR for your requested changes, I will definitely review and help it get merged. If you cannot, I can't guarantee any sort of timeline that I can do the work but i'm happy to receive issues and be aware of them. It's possible that I will find time to take care of them. I'm not 100% sure what happened to the other PR from Monish to support more forms but that was definitely an interesting idea.

I just gave this a reaaally quick and dirty test in CiviCRM 5.18.alpha1 and the basic features all seem to be functioning. I had to clear caches before the settings page would load up.

I'll close this for now, I think it is answered. Please feel free to open other issues if you end up using it!
